services:
  - type: web
    name: v8-academia
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        value: https://v8-academia-1.onrender.com
